### ISSUE TITLE
NodeJS ChargeRequest body setting incorrectly

### ISSUE THREAD

**Issue by squibbleFish** [square/connect-api-examples#120]
I'm attempting to follow the docs outlines here for creating a charge, https://github.com/square/connect-javascript-sdk/blob/master/docs/TransactionsApi.md#charge. According to this, the docs show setting the `body` of `.charge` to an object following the properties found here, https://github.com/square/connect-javascript-sdk/blob/master/docs/ChargeRequest.md#idempotencykeys

I keep running into an issue where setting the object like such
```js
const b = {
    card_nonce: nonce,
    amount_money: {
      amount: parseInt(amount),
      currency: 'USD',
    },
    idempotency_key: key,
  };
```
and then setting the charge like 
```js
const body = new SquareConnect.ChargeRequest(b);
transactionsApi.charge(square.locationID, body).then()
```
It will error out stating that the `idempotency_key` is not a string. When looking at the data being set in `ChargeRequest`, I'm seeing that prop `data` being set on the charge looks like 
```js
"data": {
                    "idempotency_key": {
                        "card_nonce": "e23hjedncsd",
                        "amount_money": {
                            "amount": 17500,
                            "currency": "USD"
                        },
                        "idempotency_key": "6bf315bf4386c743072a7a33a7ab79a42234214e106c377c36dd4bbf44c6c5a089b91e4af5fbac72643bbe44a86dc6e069a90fc51707e86dcb8a9a7266235279"
                    }
                },
```
Any help you can provide would be helpful. I'm not understanding why the charge API is setting the key incorrectly.

**Comment by StephenJosey** [comment]
You're creating the `ChargeRequest` wrong. The first parameter is `idempotency_key`, which can be seen here: https://github.com/square/connect-javascript-sdk/blob/master/src/model/ChargeRequest.js#L35

You don't need to do:
`const body = new SquareConnect.ChargeRequest(b);`
You can just do:
`transactionsApi.charge(square.locationID, b).then()` (pass in the original body instead of creating a `ChargeRequest`).

Please let me know if that doesn't work, or if you have any questions.
