### ISSUE TITLE
Can SqPaymentForm facilitate qualification for Square chargeback protection?

### ISSUE THREAD

**Issue by na-n** [square/connect-api-examples#122]
In the example on this repo that demonstrates a [nodejs integration of SqPaymentForm.js](https://github.com/square/connect-api-examples/blob/master/connect-examples/v2/node_payment/views/index.pug), the user is presented with the minimum fields required for a transaction: Card Number; CVV; Billing Postcode; Expiry Date. 

While this expedient form is great for a speedy integration, and a speedy transaction, is it possible to add more fields to the square payment form?

I would like the SqPaymentForm on my page to include billing address and/or shipping address, and buyer email address, as this would allow my websites transactions to qualify for Square Chargeback protection. 

A secondary wish would be for the SqPaymentForm to facilitate the buyers given name, last name, and title, as this would be all the data that I really need to collect. 

For example, will this give me an email input for the buyer_email_address with validity checking, if placed in a `sq-payment-form` div?
```
    div(class="sq-field sq-field--in-wrapper")
        label(class="sq-label") Email Address
        div(id="sq-buyer-email-address")
```
(along with some extension to the SqPaymentForm construction code..)
```
    paymentForm = new SqPaymentForm({
        applicationId: applicationId,
        locationId: locationId,

        inputClass: 'sq-input',
        inputStyles: _squareInputStyles,

        // Initialize a field for the buyers email address
        buyerEmailAddress: {
            elementId: 'sq-buyer-email-address'
        },
        ......
```

It would be brilliant news if SqPaymentForm can validate these fields also. 

(At the moment I'm trying to process two forms in an angularjs application on one button press..)

Perhaps this is already possible, perhaps it is not?

Thanks :)

**Comment by StephenJosey** [comment]
Hi @na-n, so you definitely _can_ add additional fields, but they will not necessarily be a part of the payment form. What I mean is that, the Square Payment Form is essentially the four fields you mentioned (card number, expiration, CVV, and postal). Anything beyond that is out of the Payment Form's scope, so if you wanted to add an email address for instance, you can definitely do so, but the Payment Form will not handle checking the validity, or even submitting it properly. However, since the Payment Form is just those fields, you can definitely add more fields and they all belong to the same form, the Payment Form will simply ignore the other fields (and it's up to you to handle them appropriately).

At this point, you'd probably want to look at our `Customers` API, and basically pass that information to the `CreateCustomer` endpoint to create a new customer with the email address, address, etc. Then you can actually attach the `customer_id` to the `Charge` request so that the customer is assigned to that particular transaction.

For more information on linking a customer, please see our docs: https://docs.connect.squareup.com/payments/transactions/setup#optional-link-a-square-customer-object-id

Definitely let me know if you have additional questions, though!

**Comment by StephenJosey** [comment]
Closing for now, but please feel free to ask follow-up questions.
