### ISSUE TITLE
Create Angular 2+ example

### ISSUE THREAD

**Issue by jitterbox** [square/connect-api-examples#65]
You had some old Angular JS (1) front-end code inside of your Rails example, but that seems to have been removed at some point.  StackOverflow turns up a couple of scattered cases in which devs seem have issues with iframes and the need to create custom typings to use SqPaymentForm...can you please provide a working example for modern Angular apps?

**Comment by StephenJosey** [comment]
Hi @jitterbox sorry about that! We're constantly improving our examples, and decided to remove those due to being outdated. We are definitely in the process of getting more examples out that show a variety of solutions, but at this time we do not have an example available in Angular 2. If you're receiving a particular error, please feel free to let us know and we can try to help out!
